//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nsi_VSN.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class vsndbEntities : DbContext
    {
        public vsndbEntities()
            : base("name=vsndbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<comment> comments { get; set; }
        public DbSet<like> likes { get; set; }
        public DbSet<message> messages { get; set; }
        public DbSet<notification_types> notification_types { get; set; }
        public DbSet<notification> notifications { get; set; }
        public DbSet<post_types> post_types { get; set; }
        public DbSet<post> posts { get; set; }
        public DbSet<role> roles { get; set; }
        public DbSet<user> users { get; set; }
    }
}
