//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nsi_VSN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class notification
    {
        public int notification_id { get; set; }
        public System.DateTime notificationTime { get; set; }
        public int notificationType_id { get; set; }
        public int notificator_id { get; set; }
        public string seen { get; set; }
        public int postNotification_id { get; set; }
    
        public virtual notification_types notification_types { get; set; }
        public virtual user user { get; set; }
        public virtual post post { get; set; }
    }
}
