//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nsi_VSN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class post
    {
        public post()
        {
            this.comments = new HashSet<comment>();
            this.likes = new HashSet<like>();
            this.notifications = new HashSet<notification>();
        }
    
        public int post_id { get; set; }
        public string title { get; set; }
        public string postText { get; set; }
        public byte[] postImage { get; set; }
        public int publisher_id { get; set; }
        public int postType_id { get; set; }
        public System.DateTime publishTime { get; set; }
        public string visible { get; set; }
    
        public virtual ICollection<comment> comments { get; set; }
        public virtual ICollection<like> likes { get; set; }
        public virtual ICollection<notification> notifications { get; set; }
        public virtual post_types post_types { get; set; }
        public virtual user user { get; set; }
    }
}
