//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nsi_VSN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class post_types
    {
        public post_types()
        {
            this.posts = new HashSet<post>();
        }
    
        public int postType_id { get; set; }
        public string textTypePost { get; set; }
    
        public virtual ICollection<post> posts { get; set; }
    }
}
